name: SVN pull
on:
  workflow_dispatch:

  schedule:
    - cron: '30 3 * * 3'
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -f 1:2.25.1-1ubuntu3.2 git=1:2.25.1-1ubuntu3.2 git-svn=1:2.25.1-1ubuntu3.2
      - name: Copy
        run: |
          git svn rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
