name: SVN pull
on:
  workflow_dispatch:

  schedule:
    - cron: '30 3 * * 3'
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove git
          sudo apt-get install -f git-svn
      - name: Copy
        run: |
          git svn rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
