name: SVN pull
on:
  workflow_dispatch:
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-svn
      - name: Copy
        run: |
          git svn clone --trunk= --branches=branches --prefix=svn/ http://svn.osdn.net/svnroot/exewrap/
      - name: Push changes
        uses: ad-m/github-push-action@master
